### DISCUSSION TITLE
Angular - Components with Styling - Adding Bootstrap to an Angular Project

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/angular#12] [Tasks]
Create an Angular app called `login-app-with-bootstrap`. 

Create the login page with a login form and a navbar. The navbar link texts should come from the component class and the structure should be defined in the component template.

Use Bootstrap navbar and form styling.

**Comment by uzma23** [comment]
### app.component.html
```html
<h1 class="top small-top">Header</h1>
<app-navbar> </app-navbar>
<app-main> </app-main>
<app-footer> </app-footer>
```
### navbar.component.html
```html
<nav>
  <ul style="color: white">
    <li><a href="#home">Home</a></li>
    <li><a href="#team">Our Team</a></li>
    <li><a href="#project">Project</a></li>
    <li><a href="#contact">Contact</a></li>
    <li style="float: right">
      <input type="text" placeholder="Search Query" class="search-box" />
      <input type="button" value="Go!" class="go-btn" />
    </li>
  </ul>
</nav>
```
### footer.component.html
```html
<footer class="footer small-footer">
  &#169; Copyright 2050 by nobody.All rights reserved.
</footer>

```

### main.component.html
```html
<div class="cont123">
  <app-article></app-article>
  <app-aside></app-aside>
</div>

```

### article.component.html
```html
<div class="content">
  <h1
    style="
      text-align: center;
      font-family: Brush Script MT, Brush Script Std, cursive;
    "
  >
    Article Heading
  </h1>
  <section>
    <p>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta, eum
      aperiam velit accusantium libero dicta? Minima odio laborum minus
      cupiditate sed quo nesciunt iusto possimus blanditiis facilis consequatur,
      aliquid iste nobis iure facere beatae ex natus laudantium quasi dolorem at
      perferendis? Dolorem, saepe expedita? Itaque fuga sunt beatae tempore
      voluptates.
    </p>
  </section>

  <section>
    <h2 style="font-family: Brush Script MT, Brush Script Std, cursive">
      Sub section
    </h2>
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Id consectetur
      accusamus necessitatibus quibusdam accusantium? Quibusdam, maiores alias?
      Dolor, ex accusamus!
    </p>
  </section>

  <section>
    <h2 style="font-family: Brush Script MT, Brush Script Std, cursive">
      Another Sub section
    </h2>
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Id consectetur
      accusamus necessitatibus quibusdam accusantium? Quibusdam, maiores alias?
      Dolor, ex accusamus!
    </p>
  </section>
</div>

```

### aside.component.html
```html
<div class="sidebar">
  <h1
    class="head"
    style="font-family: Brush Script MT, Brush Script Std, cursive"
  >
    Related
  </h1>
  <nav>
    <ul class="small-list list-big">
      <li><a href="#">Oh I do like to be beside the sea.</a></li>
      <li><a href="#">Although i the north of England</a></li>
      <li><a href="#">Its never stop rainning</a></li>
      <br />
      <li><a href="#">Oh well...</a></li>
    </ul>
  </nav>
</div>

```

### styles.css
```css
body{
    background-color: gray;
    border: 12px solid gray;
    margin: 10px;
    padding: 10px;
  }

  nav {
      background-color: rgb(212, 76, 187);
    }

    nav > ul {
        list-style-type: none;
        margin: 0;
        padding: 20px;
        overflow: hidden;
        display: flex;
        flex-wrap: wrap;
    }

    nav > ul > li {
        margin: auto;
    }

    li a:hover {
      background-color: rgb(219, 203, 203);
    }

    .content{
        grid-area: main;
        background-color:rgba(240, 248, 255, 0.952);;
        padding: 10px  ;
        margin: 10px 10px 10px  0px;
        
    }

  @media only screen and (max-width: 599px){
    h1.small-top{
    text-align: center;
    color: aliceblue;
    font-family: Brush Script MT, Brush Script Std, cursive;
    font-size: 25px;
    padding-bottom: 0px;
    margin-bottom: 0px;
    }
    nav {
      background-color: rgb(189, 159, 26);
    }
    nav > ul {
        flex-direction: column;
    }

    .small-sidebar{
        grid-area: rsideBar;
        background-color: rgb(226, 43, 211);
        margin: 10px 0px 10px 10px; 
    }

    .small-sidebar > li {
      display:block ;
    }

    .small-content{
        grid-area: main;
        background-color:rgba(247, 248, 249, 0.952);;
        padding: 10px  ;
        margin: 10px 10px 10px  0px;     
    }
    
    .small-list  {
      flex-direction: column;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    .small-footer{
      background-color: aliceblue;
      margin-top: 25px;
    }
  }
  
  @media only screen and (min-width: 600px) {
    h1.top{
    text-align: center;
    color: aliceblue;
    font-family: Brush Script MT, Brush Script Std, cursive;
    font-size: 50px;
    padding-bottom: 0px;
    margin-bottom: 0px;
  }

    .sidebar{
        float: right;
        grid-area: rsideBar;
        background-color: rgb(226, 43, 211);
        margin: 10px 0px 10px 10px;
    }
    
    
    .cont123{
        display: flex;
    }
    
    li {
        float: left;
    }
    
    li a.list-big {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }
    
    li a:hover {
        background-color: rgb(219, 203, 203);
    }
    footer{
        background-color: aliceblue;
        margin-top: 25px;
    }
}

```

**Comment by Kuntapaliwal** [comment]
## app.component.html

```html
<app-login-navigation-bar></app-login-navigation-bar>
<app-login-body></app-login-body>
<app-login-footer></app-login-footer>
```

## Login page body

```html
<main class="col-md-5 mx-auto mt-4">
    <header class="text-center">
        <h1 class="display-4 text-primary text-uppercase">LOGIN</h1>
        <h6 class="text-secondary">Enter your credentials</h6>
    </header>
    <hr />

    <section>
        <form action="register-backend" method="GET" class="font-weight-bold">
            <!-- Email -->
            <div id="emailField" name="emailField" class="form-group">
                <label for="email">Email</label><br />
                <input type="email" id="email" name="email" class="form-control" placeholder="abc@xyz.com" autofocus
                    required />
            </div>

            <!-- Password -->
            <div id="passwordField" name="passwordField" class="form-group">
                <label for="password">Password</label><br />
                <input type="password" id="password" name="password" class="form-control" required />
            </div>

            <!-- Captcha -->
            <div id="captcha" name="captcha" class="row form-group">
                <div id="captchaCodeField" name="captchaCodeField" class="col-lg-6">
                    <label for="captchaCode">Captcha Code</label><br />
                    <input type="text" id="captchaCode" name="captchaCode"
                        class="form-control font-weight-bold font-italic text-primary bg-warning" value="Q23f42"
                        readonly />
                </div>

                <div id="captchaInputField" name="captchaInputField" class="col-lg-6">
                    <label for="captchaInput">Enter Captcha</label><br />
                    <input type="text" id="captchaInput" name="captchaInput" class="form-control" autocomplete="off"
                        autofocus required />
                </div>
            </div>

            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="keepMeSignedInCheck" />
                <label class="form-check-label font-weight-normal" for="keepMeSignedInCheck">
                    Keep me signed in
                </label>
            </div>

            <!-- Submit Button -->
            <div id="loginButton" class="my-4">
                <input type="login" value="Login" class="btn btn-block btn-primary" />
            </div>
        </form>
    </section>
</main>
```

## login page navBar


```html
<nav class="navbar navbar-expand-lg navbar-fixed-top navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="#0">
        Sporty
        <img src="../../../Assets/Images/images (1).png" alt="" width="85px">Shoes
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">


        <ul class="navbar-nav offset-8">
            <li class="nav-item">
                <a href="#" class="nav-link ">
                    <strong>Contacts</strong>
                </a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link active">
                    <strong>LogIn</strong>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <strong>SignUp</strong>
                </a>
            </li>
        </ul>


    </div>
</nav>
```


## login page footer


```html
<footer class="page-footer font-small indigo my-2">

    <!-- Footer Links -->
    <div class="container text-center text-md-left" style="color: white">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Very long link 1</a>
                    </li>
                    <li>
                        <a href="#!">Very long link 2</a>
                    </li>
                    <li>
                        <a href="#!">Very long link 3</a>
                    </li>
                    <li>
                        <a href="#!">Very long link 4</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Link 1</a>
                    </li>
                    <li>
                        <a href="#!">Link 2</a>
                    </li>
                    <li>
                        <a href="#!">Link 3</a>
                    </li>
                    <li>
                        <a href="#!">Link 4</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Link 1</a>
                    </li>
                    <li>
                        <a href="#!">Link 2</a>
                    </li>
                    <li>
                        <a href="#!">Link 3</a>
                    </li>
                    <li>
                        <a href="#!">Link 4</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Link 1</a>
                    </li>
                    <li>
                        <a href="#!">Link 2</a>
                    </li>
                    <li>
                        <a href="#!">Link 3</a>
                    </li>
                    <li>
                        <a href="#!">Link 4</a>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" style="color: white">© 2020 Copyright:
        <a href="/" style="color: white"> SportyShoes.com</a>
    </div>
    <!-- Copyright -->

</footer>
```

## style.css

```css
/* You can add global styles to this file, and also import other style files */
/* You can add global styles to this file, and also import other style files */
body {
    background-color: rgb(180, 214, 245);
}

ul>li>a {
    color: white;
}

nav,
footer {
    background-color: rgb(89, 145, 234);
}


```

## angular.json

 "styles": ["../BootStrapLoginPagwWithAngular/node_modules/bootstrap/dist/css/bootstrap.css",
              "src/styles.css"
            ],
            "scripts": ["../BootStrapLoginPagwWithAngular/node_modules/bootstrap/dist/js/bootstrap.js"]
          },

**Comment by ghost** [comment]
**app.component.html**
```html
<div class="com123">
    <app-header></app-header>
    <app-main></app-main>
    <app-footer></app-footer> 
</div>
```
**header.component.html**
```html
<ul>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#">Sign up</a></li>
</ul>
```
**header.component.css**
```css
ul {
  list-style-type: none;
  margin: 0;
  padding: 0px;
  overflow: hidden;
  background-color: rgb(21, 21, 66);
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
 font-size:20px;
  text-align: center;
  padding: 10px 20px;
  text-decoration: none;
}
.active{
background-color:rgb(21, 21, 66);
color: white;
}
li a:hover {
  background-color: orange;
  color: white;
}
```
**main.component.html**
```html
<section class="vh-5" style="background-color: #d4dbda;">
  <div class="container py-5 h-50">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h4 class="mb-5">Sign in</h4>
            <div class="form-outline mb-2">
              <input type="email" id="typeEmailX-2" class="form-control form-control-lg" />
              <label class="form-label" for="typeEmailX-2">Email</label>
            </div>
            <div class="form-outline mb-2">
              <input type="password" id="typePasswordX-2" class="form-control form-control-lg" />
              <label class="form-label" for="typePasswordX-2">Password</label>
            </div>
            <div class="form-check d-flex justify-content-start mb-4">
              <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
              <label class="form-check-label" for="form1Example3"> Remember password </label>
            </div>
            <button class="btn btn-lg btn-block btn btn-outline-dark" type="submit" style="background-color:rgb(212, 162, 25)">Login</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
```
**footer.component.html**
```html
<footer class="page-footer font-small text-white" style="background-color: rgb(21, 21, 66)">
    <div class="footer-copyright text-center py-3">© 1996-2022, Amazon.com, Inc. or its affiliates</div>
</footer>   
```

## screenshot
![Web capture_27-7-2022_143122_localhost](https://user-images.githubusercontent.com/53044554/181208520-60ea1b84-3fed-459b-8942-789d884bb425.jpeg)
