### DISCUSSION TITLE
Angular - One-way Binding - Interpolation & Event Binding - Changing partial page content on (click) event

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/angular#16] [Tasks]
You are the given following website:

![image](https://user-images.githubusercontent.com/60097560/181187894-8526faaa-6a96-46d8-9012-7b9fc98f367a.png)

You are currently on the "Home" page.

Define functions in the component class(es) which will change the content of the **main** section of the page depending on which navigation link is clicked. The header and the footer should remain the same.

The functions will be called via "Event Binding" from the template.

**Comment by PurnaPichuka** [comment]
.html file
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Article Web Page</title>
  </head>
  <body>
    <h1 class="text-center">Header</h1>
    <div class="container">
      <div class="grid-container">
        <div class="item1">
          <nav class="header">
            <ul>
              <li><button class="btn" (click)="openHome()">Home</button></li>
              <li>
                <button class="btn" (click)="openArticle()">Articles</button>
              </li>
              <li>
                <button class="btn" (click)="openContact()">Contact</button>
              </li>
              <li>
                <input
                  type="search"
                  name="search"
                  id="search"
                  placeholder="Search query"
                />
              </li>
              <li><input type="button" name="go" id="go" value="GO!" /></li>
            </ul>
          </nav>
        </div>
        <!--Home-->
        <div class="item2">
          <div class="" id="himalayas" *ngIf="showHome">
            <h1 class="text-center">The Himalayas</h1>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Repudiandae beatae a ratione quod
              veritatis! Nisi molestias delectus consequatur architecto quam?
              Sit voluptas nemo voluptates provident laborum veritatis numquam
              vel quaerat.
            </p>
            <h2>Himalayas-1</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>

            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam
              praesentium ad laborum, non quibusdam consectetur reiciendis
              voluptatum debitis veritatis, accusamus recusandae ipsum, quam
              tempora ab iusto ratione nostrum consequatur omnis?
            </p>
            <h2>Himalayas-2</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>
          </div>
          <!--Articles-->
          <div class="" id="river" *ngIf="showArticles">
            <h1 class="text-center">River & Sea</h1>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Repudiandae beatae a ratione quod
              veritatis! Nisi molestias delectus consequatur architecto quam?
              Sit voluptas nemo voluptates provident laborum veritatis numquam
              vel quaerat.
            </p>
            <h2>River</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>

            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam
              praesentium ad laborum, non quibusdam consectetur reiciendis
              voluptatum debitis veritatis, accusamus recusandae ipsum, quam
              tempora ab iusto ratione nostrum consequatur omnis?
            </p>
            <h2>Sea</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet
              repellendus minima voluptatibus magnam optio sapiente veritatis
              modi sit porro quasi, ratione, voluptates eaque libero rem
              accusamus ipsa eum perferendis ipsam.
            </p>
          </div>

          <!--Contact-->
          <div class="" id="contact" *ngIf="showContact">
            <h1 class="text-center">Contact Us</h1>
            <pre>
              Hey there, thank you for visiting our website. We looking forward
              to connecting with you.
              
              Please give us up to 72 hours torespond before resending the email. 
              
              Please note that we DO NOTaccept guest posts. If you send us an 
              inquiry with that, we will simply mark your email as spam. 
              
              Thanks for your understanding, andonce again thanks for checking out 
              our site. 
              
              We look forward to hearing from you!
            </pre>
            <form class="form-group">
              <div>
                <label for="name"><b>Name*:</b></label>
                <input type="text" class="form-control" />
              </div>
              <br />
              <div>
                <label for="name"><b>Email*:</b></label>
                <input type="text" class="form-control" />
              </div>
              <br />
              <div>
                <label for="name"><b>Message*:</b></label>
                <textarea type="text" class="form-control"></textarea>
              </div>
              <br />
              <div>
                <!-- <label for="name"><b>Email*:</b></label> -->
                <input type="button" value="Submit" />
              </div>
            </form>
          </div>
        </div>

        <div class="item3">
          <!--sidebar-1-->
          <div class="" *ngIf="showHomeSideBar">
            <aside>
              <h1>Related to Himalayas</h1>
              <ul>
                <li><a href="#">Oh I do like to be beside the seaside</a></li>
                <li><a href="#">Oh I do like to be beside the sea</a></li>
                <li><a href="#">Although in the north of England</a></li>
                <li><a href="#">I never stops raining</a></li>
                <li><a href="#">oh well....</a></li>
              </ul>
            </aside>
          </div>
          <!--sidebar-2-->
          <div class="" *ngIf="showArticlesSideBar">
            <aside>
              <h1>Related to Rivers&Sea</h1>
              <ul>
                <li><a href="#">Oh I do like to be beside the seaside</a></li>
                <li><a href="#">Oh I do like to be beside the sea</a></li>
                <li><a href="#">Although in the north of England</a></li>
                <li><a href="#">I never stops raining</a></li>
                <li><a href="#">oh well....</a></li>
              </ul>
            </aside>
          </div>
          <!--sidebar-3-->
          <div class="" *ngIf="showContactSideBar">
            <aside>
              <h1>Related to Contacts</h1>
              <ul>
                <li><a href="#">Oh I do like to be beside the seaside</a></li>
                <li><a href="#">Oh I do like to be beside the sea</a></li>
                <li><a href="#">Although in the north of England</a></li>
                <li><a href="#">I never stops raining</a></li>
                <li><a href="#">oh well....</a></li>
              </ul>
            </aside>
          </div>
        </div>

        <div class="item4">
          <footer>
            <p class="text-center">
              @copyright 2050 by nobody. All rigths reserved
            </p>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

```
.ts file
```js
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-changing-partial-page-content-on-click-event',
  templateUrl: './changing-partial-page-content-on-click-event.component.html',
  styleUrls: ['./changing-partial-page-content-on-click-event.component.css']
})
export class ChangingPartialPageContentOnClickEventComponent implements OnInit {

  public showHome:boolean = true;
  public showArticles:boolean = false;
  public showContact:boolean = false;

  public showHomeSideBar:boolean = true;
  public showArticlesSideBar:boolean = false;
  public showContactSideBar:boolean = false;


  openArticle(){
      this.showHome = false;
      this.showArticles = true;
      this.showHomeSideBar = false;
      this.showArticlesSideBar = true;
      this.showContact=false;
      this.showContactSideBar=false;
  }

  openHome(){
      this.showHome = true;
      this.showArticles = false;
      this.showHomeSideBar = true;
      this.showArticlesSideBar = false;
      this.showContact=false;
      this.showContactSideBar=false;
  }

  openContact(){
    this.showContact=true;
    this.showContactSideBar=true;
    this.showHome = false;
    this.showArticles = false;
    this.showHomeSideBar = false;
    this.showArticlesSideBar = false;
  }

  constructor() { }

  ngOnInit(): void {
  }

}

```
.css file
```css

      body {
        background-color: gray;
      }

      a {
        color: black;
        /* text-decoration: inherit; */
      }

      .header > ul > li {
        display: inline;
        padding: 30px;
        font-size: 20px;
        
      }

      .btn:hover {
        background: #eee;
      }
      .btn {
        font-size: 20px;
      }

      #search {
        margin-left: 200px;
        margin-top: 10px;
      }
      #go {
        background-color: black;
        color: white;
      }

      .item1 {
        grid-area: header;
        padding: 10px;
        background-color: rgb(15, 165, 176);
      }
      .item2 {
        grid-area: main;
        padding: 10px;
        background-color: white;
      }
      .item3 {
        grid-area: sidebar;
        padding: 10px;
        background-color: rgb(15, 165, 176);
      }
      .item4 {
        grid-area: footer;
        padding: 10px;
        background-color: white;
      }

      .grid-container {
        display: grid;
        grid-template-areas:
          "header header header header"
          "main main main sidebar"
          "main main main sidebar"
          "footer footer footer footer";
        grid-gap: 10px;
        padding: 10px;
      }

```

![image](https://user-images.githubusercontent.com/111061290/195927412-1da971e2-5b5e-4555-9cbd-309eff409810.png)

![image](https://user-images.githubusercontent.com/111061290/195927599-859af7fa-f755-460b-aedf-25ea8e6cbc0b.png)

![image](https://user-images.githubusercontent.com/111061290/195927686-ea1ec150-c1f6-49c3-ac35-841566931140.png)
